name = "heizbox-backend"
main = "src/index.ts"
compatibility_date = "2025-04-01"
account_id = "3ebe65c531d29ca9dd24e28af3da9a82"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "db" # This is the binding name in your Worker code
database_name = "heizbox"
database_id = "0756a6f6-e6de-43b0-918d-115e81f0a9cc"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "fa8331445aee4fb89d28386b5229a6a2"

[dev]
local_protocol = "http"
web_sockets = true

[observability.logs]
enabled = true