name = "heizbox"
main = "src/worker/index.ts"
compatibility_date = "2025-04-01"
account_id = "3ebe65c531d29ca9dd24e28af3da9a82"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "db"
database_name = "heizbox"
database_id = "0756a6f6-e6de-43b0-918d-115e81f0a9cc"

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "fa8331445aee4fb89d28386b5229a6a2"

[dev]
local_protocol = "http"

[observability.logs]
enabled = true